INSERT INTO states (ID, name, abbreviation) values (1, 'Alabama', 'AL'); 
INSERT INTO states (ID, name, abbreviation) values (2, 'Alaska', 'AK'); 
INSERT INTO states (ID, name, abbreviation) values (3, 'American Samoa', 'AS'); 
INSERT INTO states (ID, name, abbreviation) values (4, 'Arizona', 'AZ'); 
INSERT INTO states (ID, name, abbreviation) values (5, 'Arkansas', 'AR'); 
INSERT INTO states (ID, name, abbreviation) values (6, 'California', 'CA'); 
INSERT INTO states (ID, name, abbreviation) values (7, 'Colorado', 'CO'); 
INSERT INTO states (ID, name, abbreviation) values (8, 'Connecticut', 'CT'); 
INSERT INTO states (ID, name, abbreviation) values (9, 'Delaware', 'DE'); 
INSERT INTO states (ID, name, abbreviation) values (10, 'District Of Columbia', 'DC'); 
INSERT INTO states (ID, name, abbreviation) values (11, 'Federated States Of Micronesia', 'FM'); 
INSERT INTO states (ID, name, abbreviation) values (12, 'Florida', 'FL'); 
INSERT INTO states (ID, name, abbreviation) values (13, 'Georgia', 'GA'); 
INSERT INTO states (ID, name, abbreviation) values (14, 'Guam', 'GU'); 
INSERT INTO states (ID, name, abbreviation) values (15, 'Hawaii', 'HI'); 
INSERT INTO states (ID, name, abbreviation) values (16, 'Idaho', 'ID'); 
INSERT INTO states (ID, name, abbreviation) values (17, 'Illinois', 'IL'); 
INSERT INTO states (ID, name, abbreviation) values (18, 'Indiana', 'IN'); 
INSERT INTO states (ID, name, abbreviation) values (19, 'Iowa', 'IA'); 
INSERT INTO states (ID, name, abbreviation) values (20, 'Kansas', 'KS'); 
INSERT INTO states (ID, name, abbreviation) values (21, 'Kentucky', 'KY'); 
INSERT INTO states (ID, name, abbreviation) values (22, 'Louisiana', 'LA'); 
INSERT INTO states (ID, name, abbreviation) values (24, 'Maine', 'ME'); 
INSERT INTO states (ID, name, abbreviation) values (25, 'Marshall Islands', 'MH'); 
INSERT INTO states (ID, name, abbreviation) values (26, 'Maryland', 'MD'); 
INSERT INTO states (ID, name, abbreviation) values (27, 'Massachusetts', 'MA'); 
INSERT INTO states (ID, name, abbreviation) values (28, 'Michigan', 'MI'); 
INSERT INTO states (ID, name, abbreviation) values (29, 'Minnesota', 'MN'); 
INSERT INTO states (ID, name, abbreviation) values (30, 'Mississippi', 'MS'); 
INSERT INTO states (ID, name, abbreviation) values (31, 'Missouri', 'MO'); 
INSERT INTO states (ID, name, abbreviation) values (32, 'Montana', 'MT'); 
INSERT INTO states (ID, name, abbreviation) values (33, 'Nebraska', 'NE'); 
INSERT INTO states (ID, name, abbreviation) values (34, 'Nevada', 'NV'); 
INSERT INTO states (ID, name, abbreviation) values (35, 'New Hampshire', 'NH'); 
INSERT INTO states (ID, name, abbreviation) values (36, 'New Jersey', 'NJ'); 
INSERT INTO states (ID, name, abbreviation) values (37, 'New Mexico', 'NM'); 
INSERT INTO states (ID, name, abbreviation) values (38, 'New York', 'NY'); 
INSERT INTO states (ID, name, abbreviation) values (39, 'North Carolina', 'NC'); 
INSERT INTO states (ID, name, abbreviation) values (40, 'North Dakota', 'ND'); 
INSERT INTO states (ID, name, abbreviation) values (41, 'Northern Mariana Islands', 'MP'); 
INSERT INTO states (ID, name, abbreviation) values (42, 'Ohio', 'OH'); 
INSERT INTO states (ID, name, abbreviation) values (43, 'Oklahoma', 'OK'); 
INSERT INTO states (ID, name, abbreviation) values (44, 'Oregon', 'OR'); 
INSERT INTO states (ID, name, abbreviation) values (45, 'Palau', 'PW'); 
INSERT INTO states (ID, name, abbreviation) values (46, 'Pennsylvania', 'PA'); 
INSERT INTO states (ID, name, abbreviation) values (47, 'Puerto Rico', 'PR'); 
INSERT INTO states (ID, name, abbreviation) values (48, 'Rhode Island', 'RI'); 
INSERT INTO states (ID, name, abbreviation) values (49, 'South Carolina', 'SC'); 
INSERT INTO states (ID, name, abbreviation) values (50, 'South Dakota', 'SD'); 
INSERT INTO states (ID, name, abbreviation) values (51, 'Tennessee', 'TN'); 
INSERT INTO states (ID, name, abbreviation) values (52, 'Texas', 'TX'); 
INSERT INTO states (ID, name, abbreviation) values (53, 'Utah', 'UT'); 
INSERT INTO states (ID, name, abbreviation) values (54, 'Vermont', 'VT'); 
INSERT INTO states (ID, name, abbreviation) values (55, 'Virgin Islands', 'VI'); 
INSERT INTO states (ID, name, abbreviation) values (56, 'Virginia', 'VA'); 
INSERT INTO states (ID, name, abbreviation) values (57, 'Washington', 'WA'); 
INSERT INTO states (ID, name, abbreviation) values (58, 'West Virginia', 'WV'); 
INSERT INTO states (ID, name, abbreviation) values (59, 'Wisconsin', 'WI'); 
INSERT INTO states (ID, name, abbreviation) values (60, 'Wyoming', 'WY'); 
