INSERT INTO products (ID, name) values (1, "Mortgage"); 
INSERT INTO products (ID, name) values (2, "Credit reporting"); 
INSERT INTO products (ID, name) values (3, "Consumer Loan"); 
INSERT INTO products (ID, name) values (4, "Credit card"); 
INSERT INTO products (ID, name) values (5, "Debt collection"); 
INSERT INTO products (ID, name) values (6, "Student loan"); 
INSERT INTO products (ID, name) values (7, "Bank account or service"); 
INSERT INTO products (ID, name) values (8, "Other financial service"); 
INSERT INTO products (ID, name) values (9, "Prepaid card"); 
INSERT INTO products (ID, name) values (10, "Money transfers"); 
INSERT INTO products (ID, name) values (11, "Credit reporting, credit repair services, or other personal consumer reports"); 
INSERT INTO products (ID, name) values (12, "Payday loan"); 
INSERT INTO products (ID, name) values (13, "Checking or savings account"); 
INSERT INTO products (ID, name) values (14, "Money transfer, virtual currency, or money service"); 
INSERT INTO products (ID, name) values (15, "Credit card or prepaid card"); 
INSERT INTO products (ID, name) values (16, "Vehicle loan or lease"); 
INSERT INTO products (ID, name) values (17, "Payday loan, title loan, or personal loan"); 
INSERT INTO products (ID, name) values (18, "Virtual currency"); 
