INSERT INTO issues (ID, type) values (1, "Loan modification,collection,foreclosure"); 
INSERT INTO issues (ID, type) values (2, "Incorrect information on credit report"); 
INSERT INTO issues (ID, type) values (3, "Managing the loan or lease"); 
INSERT INTO issues (ID, type) values (4, "Bankruptcy"); 
INSERT INTO issues (ID, type) values (5, "Communication tactics"); 
INSERT INTO issues (ID, type) values (6, "Loan servicing, payments, escrow account"); 
INSERT INTO issues (ID, type) values (7, "Improper contact or sharing of info"); 
INSERT INTO issues (ID, type) values (8, "Credit reporting company's investigation"); 
INSERT INTO issues (ID, type) values (9, "Repaying your loan"); 
INSERT INTO issues (ID, type) values (10, "Disclosure verification of debt"); 
INSERT INTO issues (ID, type) values (11, "Closing/Cancelling account"); 
INSERT INTO issues (ID, type) values (12, "Application, originator, mortgage broker"); 
INSERT INTO issues (ID, type) values (13, "Cont'd attempts collect debt not owed"); 
INSERT INTO issues (ID, type) values (14, "Making/receiving payments, sending money"); 
INSERT INTO issues (ID, type) values (15, "Settlement process and costs"); 
INSERT INTO issues (ID, type) values (16, "Delinquent account"); 
INSERT INTO issues (ID, type) values (17, "Account opening, closing, or management"); 
INSERT INTO issues (ID, type) values (18, "Other fee"); 
INSERT INTO issues (ID, type) values (19, "Late fee"); 
INSERT INTO issues (ID, type) values (20, "Credit line increase/decrease"); 
INSERT INTO issues (ID, type) values (21, "Identity theft / Fraud / Embezzlement"); 
INSERT INTO issues (ID, type) values (22, "Deposits and withdrawals"); 
INSERT INTO issues (ID, type) values (23, "Taking/threatening an illegal action"); 
INSERT INTO issues (ID, type) values (24, "False statements or representation"); 
INSERT INTO issues (ID, type) values (25, "Problems caused by my funds being low"); 
INSERT INTO issues (ID, type) values (26, "Dealing with my lender or servicer"); 
INSERT INTO issues (ID, type) values (27, "Billing disputes"); 
INSERT INTO issues (ID, type) values (28, "Credit decision / Underwriting"); 
INSERT INTO issues (ID, type) values (29, "Improper use of my credit report"); 
INSERT INTO issues (ID, type) values (30, "Can't repay my loan"); 
INSERT INTO issues (ID, type) values (31, "Fraud or scam"); 
INSERT INTO issues (ID, type) values (32, "Unable to get credit report/credit score"); 
INSERT INTO issues (ID, type) values (33, "Rewards"); 
INSERT INTO issues (ID, type) values (34, "Other"); 
INSERT INTO issues (ID, type) values (35, "Shopping for a loan or lease"); 
INSERT INTO issues (ID, type) values (36, "Problems when you are unable to pay"); 
INSERT INTO issues (ID, type) values (37, "Using a debit or ATM card"); 
INSERT INTO issues (ID, type) values (38, "APR or interest rate"); 
INSERT INTO issues (ID, type) values (39, "Taking out the loan or lease"); 
INSERT INTO issues (ID, type) values (40, "Other transaction issues"); 
INSERT INTO issues (ID, type) values (41, "Incorrect information on your report"); 
INSERT INTO issues (ID, type) values (42, "Can't stop charges to bank account"); 
INSERT INTO issues (ID, type) values (43, "Advertising and marketing"); 
INSERT INTO issues (ID, type) values (44, "Struggling to pay mortgage"); 
INSERT INTO issues (ID, type) values (45, "Applied for loan/did not receive money"); 
INSERT INTO issues (ID, type) values (46, "Credit reporting"); 
INSERT INTO issues (ID, type) values (47, "Collection debt dispute"); 
INSERT INTO issues (ID, type) values (48, "Credit card protection / Debt protection"); 
INSERT INTO issues (ID, type) values (49, "Credit determination"); 
INSERT INTO issues (ID, type) values (50, "Privacy"); 
INSERT INTO issues (ID, type) values (51, "Credit monitoring or identity protection"); 
INSERT INTO issues (ID, type) values (52, "Money was not available when promised"); 
INSERT INTO issues (ID, type) values (53, "Managing the line of credit"); 
INSERT INTO issues (ID, type) values (54, "Wrong amount charged or received"); 
INSERT INTO issues (ID, type) values (55, "Customer service / Customer relations"); 
INSERT INTO issues (ID, type) values (56, "Unsolicited issuance of credit card"); 
INSERT INTO issues (ID, type) values (57, "Attempts to collect debt not owed"); 
INSERT INTO issues (ID, type) values (58, "Billing statement"); 
INSERT INTO issues (ID, type) values (59, "Lost or stolen money order"); 
INSERT INTO issues (ID, type) values (60, "Can't contact lender"); 
INSERT INTO issues (ID, type) values (61, "Charged fees or interest I didn't expect"); 
INSERT INTO issues (ID, type) values (62, "Balance transfer"); 
INSERT INTO issues (ID, type) values (63, "Getting a loan"); 
INSERT INTO issues (ID, type) values (64, "Received a loan I didn't apply for"); 
INSERT INTO issues (ID, type) values (65, "Shopping for a line of credit"); 
INSERT INTO issues (ID, type) values (66, "Written notification about debt"); 
INSERT INTO issues (ID, type) values (67, "Problem with a credit reporting company's investigation into an existing problem"); 
INSERT INTO issues (ID, type) values (68, "Account terms and changes"); 
INSERT INTO issues (ID, type) values (69, "Application processing delay"); 
INSERT INTO issues (ID, type) values (70, "Payoff process"); 
INSERT INTO issues (ID, type) values (71, "Cash advance fee"); 
INSERT INTO issues (ID, type) values (72, "Fees"); 
INSERT INTO issues (ID, type) values (73, "Managing, opening, or closing account"); 
INSERT INTO issues (ID, type) values (74, "Collection practices"); 
INSERT INTO issues (ID, type) values (75, "Transaction issue"); 
INSERT INTO issues (ID, type) values (76, "Unauthorized transactions/trans. issues"); 
INSERT INTO issues (ID, type) values (77, "Other service issues"); 
INSERT INTO issues (ID, type) values (78, "Problem caused by your funds being low"); 
INSERT INTO issues (ID, type) values (79, "Charged bank acct wrong day or amt"); 
INSERT INTO issues (ID, type) values (80, "Trouble during payment process"); 
INSERT INTO issues (ID, type) values (81, "Payment to acct not credited"); 
INSERT INTO issues (ID, type) values (82, "Improper use of your report"); 
INSERT INTO issues (ID, type) values (83, "Customer service/Customer relations"); 
INSERT INTO issues (ID, type) values (84, "Cash advance"); 
INSERT INTO issues (ID, type) values (85, "Forbearance / Workout plans"); 
INSERT INTO issues (ID, type) values (86, "Sale of account"); 
INSERT INTO issues (ID, type) values (87, "Dealing with your lender or servicer"); 
INSERT INTO issues (ID, type) values (88, "Applying for a mortgage"); 
INSERT INTO issues (ID, type) values (89, "Closing an account"); 
INSERT INTO issues (ID, type) values (90, "Overlimit fee"); 
INSERT INTO issues (ID, type) values (91, "Advertising, marketing or disclosures"); 
INSERT INTO issues (ID, type) values (92, "Took or threatened to take negative or legal action"); 
INSERT INTO issues (ID, type) values (93, "Threatened to contact someone or share information improperly"); 
INSERT INTO issues (ID, type) values (94, "Arbitration"); 
INSERT INTO issues (ID, type) values (95, "Incorrect/missing disclosures or info"); 
INSERT INTO issues (ID, type) values (96, "Problem with customer service"); 
INSERT INTO issues (ID, type) values (97, "Opening an account"); 
INSERT INTO issues (ID, type) values (98, "Balance transfer fee"); 
INSERT INTO issues (ID, type) values (99, "Other features, terms, or problems"); 
INSERT INTO issues (ID, type) values (100, "Problem with a purchase shown on your statement"); 
INSERT INTO issues (ID, type) values (101, "Problem with a company's investigation into an existing issue"); 
INSERT INTO issues (ID, type) values (102, "Fees or interest"); 
INSERT INTO issues (ID, type) values (103, "Adding money"); 
INSERT INTO issues (ID, type) values (104, "Incorrect exchange rate"); 
INSERT INTO issues (ID, type) values (105, "Lender repossessed or sold the vehicle"); 
INSERT INTO issues (ID, type) values (106, "Struggling to repay your loan"); 
INSERT INTO issues (ID, type) values (107, "Unable to get your credit report or credit score"); 
INSERT INTO issues (ID, type) values (108, "Problem with a purchase or transfer"); 
INSERT INTO issues (ID, type) values (109, "Unexpected/Other fees"); 
INSERT INTO issues (ID, type) values (110, "Problem with fraud alerts or security freezes"); 
INSERT INTO issues (ID, type) values (111, "Problem when making payments"); 
INSERT INTO issues (ID, type) values (112, "Other transaction problem"); 
INSERT INTO issues (ID, type) values (113, "Managing an account"); 
INSERT INTO issues (ID, type) values (114, "Convenience checks"); 
INSERT INTO issues (ID, type) values (115, "Getting a credit card"); 
INSERT INTO issues (ID, type) values (116, "Advertising and marketing, including promotional offers"); 
INSERT INTO issues (ID, type) values (117, "Problems at the end of the loan or lease"); 
INSERT INTO issues (ID, type) values (118, "Trouble using your card"); 
INSERT INTO issues (ID, type) values (119, "Lost or stolen check"); 
INSERT INTO issues (ID, type) values (120, "Closing on a mortgage"); 
INSERT INTO issues (ID, type) values (121, "Closing your account"); 
INSERT INTO issues (ID, type) values (122, "Problem with a lender or other company charging your account"); 
INSERT INTO issues (ID, type) values (123, "Other service problem"); 
INSERT INTO issues (ID, type) values (124, "Received a loan you didn't apply for"); 
INSERT INTO issues (ID, type) values (125, "Excessive fees"); 
INSERT INTO issues (ID, type) values (126, "Applying for a mortgage or refinancing an existing mortgage"); 
INSERT INTO issues (ID, type) values (127, "Credit monitoring or identity theft protection services"); 
INSERT INTO issues (ID, type) values (128, "Struggling to pay your loan"); 
INSERT INTO issues (ID, type) values (129, "Unauthorized transactions or other transaction problem"); 
INSERT INTO issues (ID, type) values (130, "Disclosures"); 
INSERT INTO issues (ID, type) values (131, "Charged fees or interest you didn't expect"); 
INSERT INTO issues (ID, type) values (132, "Trouble using the card"); 
INSERT INTO issues (ID, type) values (133, "Problem with additional add-on products or services"); 
INSERT INTO issues (ID, type) values (134, "Problem getting a card or closing an account"); 
INSERT INTO issues (ID, type) values (135, "Getting a line of credit"); 
INSERT INTO issues (ID, type) values (136, "Getting a loan or lease"); 
INSERT INTO issues (ID, type) values (137, "Can't contact lender or servicer"); 
INSERT INTO issues (ID, type) values (138, "Problem adding money"); 
INSERT INTO issues (ID, type) values (139, "Overdraft, savings, or rewards features"); 
INSERT INTO issues (ID, type) values (140, "Managing, opening, or closing your mobile wallet account"); 
INSERT INTO issues (ID, type) values (141, "Overdraft, savings or rewards features"); 
INSERT INTO issues (ID, type) values (142, "Unexpected or other fees"); 
INSERT INTO issues (ID, type) values (143, "Can't stop withdrawals from your bank account"); 
INSERT INTO issues (ID, type) values (144, "Getting the loan"); 
INSERT INTO issues (ID, type) values (145, "Lender sold the property"); 
INSERT INTO issues (ID, type) values (146, "Problem with the payoff process at the end of the loan"); 
INSERT INTO issues (ID, type) values (147, "Identity theft protection or other monitoring services"); 
INSERT INTO issues (ID, type) values (148, "Confusing or misleading advertising or marketing"); 
INSERT INTO issues (ID, type) values (149, "Confusing or missing disclosures"); 
INSERT INTO issues (ID, type) values (150, "Loan payment wasn't credited to your account"); 
INSERT INTO issues (ID, type) values (151, "Vehicle was repossessed or sold the vehicle"); 
INSERT INTO issues (ID, type) values (152, "Was approved for a loan, but didn't receive the money"); 
INSERT INTO issues (ID, type) values (153, "Problem with overdraft"); 
INSERT INTO issues (ID, type) values (154, "Lender damaged or destroyed vehicle"); 
INSERT INTO issues (ID, type) values (155, "Struggling to pay your bill"); 
INSERT INTO issues (ID, type) values (156, "Money was taken from your bank account on the wrong day or for the wrong amount"); 
INSERT INTO issues (ID, type) values (157, "Advertising"); 
INSERT INTO issues (ID, type) values (158, "Credit limit changed"); 
INSERT INTO issues (ID, type) values (159, "Was approved for a loan, but didn't receive money"); 
INSERT INTO issues (ID, type) values (160, "Property was sold"); 
INSERT INTO issues (ID, type) values (161, "Vehicle was damaged or destroyed the vehicle"); 
INSERT INTO issues (ID, type) values (162, "Problem with cash advance"); 
INSERT INTO issues (ID, type) values (163, "Lender damaged or destroyed property"); 
INSERT INTO issues (ID, type) values (164, "Problem with credit report or credit score"); 
INSERT INTO issues (ID, type) values (165, "Property was damaged or destroyed property"); 
INSERT INTO issues (ID, type) values (166, "Problem with an overdraft"); 
