version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: spin up db
          command: docker-compose -f ./docker-compose.test.yml up -d complaintdb 
      - run:
          name: wait for db to be seeded
          command: docker-compose ./docker-compose.test.yml run complaint-service ./wait-for-mysql.sh
      - run:
          name: Run tests
          command: docker-compose -f ./docker-compose.test.yml up --exit-code-from complaint-service
