version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: spin up db
          command: docker-compose -f ./docker-compose.test.yml up -d complaintdb 
      - run:
          name: wait for db
          command: docker-compose -f ./docker-compose.test.yml run complaint-service ./wait-for-mysql.sh
      - run:
          name: Run tests
          command: docker-compose -f ./docker-compose.test.yml up --exit-code-from complaint-service

  deploy:
    docker:
        - image: google/cloud-sdk:alpine
    working_directory: /home/circleci/app
    steps:
        - checkout

        - run:
            name: Authenticate with Google Cloud
            command: |
                echo $GCLOUD_KEY_JSON > /home/circleci/.gcloud-key
                gcloud auth activate-service-account --key-file=/home/circleci/.gcloud-key
        - run:
            name: configure gcloud to the correct project
            command: gcloud config set project austin-davis-test
        - run:
            name: Deploy the service to Google App Engine
            command: |
                cd ./complaint-service
                gcloud app deploy
        - run:
            name: Deploy Documentation to Google App Engine
            command: |
                cd ./doc-service
                gcloud app deploy --version="documentation"






workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
