version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=password
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0 
      - run:
          name: set up db
      - run:
          name: Run tests
          command: docker-compose -f ./docker-compose.test.yml up --exit-code-from complaint-service
